server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: physical-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.70.190:3306/student_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: app
    password: Juyi_mysql_2024
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true